baseURL = 'https://madelonterborg.netlify.app'
languageCode = 'nl-nl'
title = 'Madelon ter Borg'
theme = 'simpel'
pluralizeListTitles = 'false'
[[module.imports]]
path = "github.com/mfg92/hugo-shortcode-gallery"
#[markup]
#  [markup.goldmark]
#    [markup.goldmark.renderer]
#      unsafe = true
#[module]
#  [[module.mounts]]
#    source = 'assets'
#    target = 'assets'
#  [[module.mounts]]
#    source = 'static'
#    target = 'assets'
