backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: "Madelon ter Borg"
    label: "Portfolio"
    folder: "/content/portfolio/"
    media_folder: ""
    public_folder: ""
    create: true
    slug: "{{title}}"
    path: "{{slug}}/index"
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Jaar", name: "jaar", widget: "string" }
      - { label: "Medium", name: "medium", widget: "string" }
      - {
          label: "Youtube-Link",
          name: "link",
          widget: "object",
          required: false,
          fields:
            [
              { label: "Weblink", name: "weblink", widget: "text" },
              {
                label: "Thumbnail",
                name: "thumbnail",
                widget: "image",
                choose_url: fale,
                media_folder: "thumbnail",
                public_folder: "thumbnail",
              },
            ],
        }
      - {
          label: "Afbeeldingen",
          name: "afbeeldingen",
          widget: "list",
          field:
            {
              label: "Afbeelding",
              name: "image",
              widget: "image",
              choose_url: false,
              media_folder: "documentatie",
              public_folder: "documentatie",
            },
        }
      - { label: "Fotograaf", name: "fotograaf", widget: "text" }
      - { label: "Omschrijving", name: "body", widget: "markdown" }
  - name: "Paginas"
    label: "paginas"
    files:
      - label: "Index"
        name: "index"
        media_folder: ""
        public_folder: ""
        create: false
        editor:
          preview: false
        file: "_index.md"
        fields:
          - {
              label: "Index",
              name: "index",
              widget: "list",
              field:
                {
                  label: "Index-link",
                  name: "indexlink",
                  widget: "object",
                  field:
                      {
                        label: "Index-foto",
                        name: "indexfoto",
                        widget: "image",
                        choose_url: true,
                        media_folder: "",
                        public_folder: "",
                        hint: "zorg dat de bestandsnaam als volgt is opgedeeld: naam-van-werk.jpg"
                      }
                    ,
                },
            }
      - label: "Over"
        name: "over"
        media_folder: ""
        public_folder: ""
        create: false
        editor:
          preview: false
        file: "/content/over-madelon.md"
        fields:
          - {
              label: "Portret",
              name: "image",
              widget: "image",
              choose_url: false,
            }
          - { label: "Artist Statement", name: "body", widget: "markdown" }
          - label: "Opleidingen"
            name: "opleidingen"
            widget: "list"
            field:
              label: "Studie"
              name: "studie"
              widget: "object"
              fields:
                - { label: "Opleiding", name: "opleiding", widget: "text" }
                - { label: "Instituut", name: "plek", widget: "text" }
                - {
                    label: "Afstudeerdata",
                    name: "afstudeerdata",
                    widget: "text",
                  }
          - label: "Zichtbaarheid"
            name: "zichtbaarheid"
            widget: "list"
            field:
              label: "Tentoonstelling"
              name: "tentoonstelling"
              widget: "object"
              fields:
                - { label: "Naam", name: "naam", widget: "text" }
                - {
                    label: "Tentoonstellingsruimte",
                    name: "tentoonstellingsruimte",
                    widget: "text",
                  }
                - {
                    label: "Tentoonstellingsdata",
                    name: "tentoonstellingsdata",
                    widget: "text",
                  }
                - { label: "Soort", name: "soort", widget: "text" }
          - label: "Overig"
            name: "overig"
            required: false
            widget: "list"
            field:
              label: "Engagement"
              name: "engagement"
              widget: object'
              fields:
                - { label: "Wat", name: "wat", widget: "text" }
                - { label: "Plek", name: "plek", widget: "text" }
                - { label: "Data", name: "data", widget: "text" }
          - { label: "Email", name: "email", widget: "text" }
