backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'Madelon ter Borg'
    label: 'Portfolio'
    folder: '/content/portfolio/'
    slug: '{{title}}'
    path: '{{slug}}/'
    media_folder: ''
    public_folder: ''
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Jaar', name: 'date', widget: 'datetime' }
      - { label: 'Medium', name: 'medium', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'text', required: false }
      - { label: 'Afbeelding', name: 'afbeeldingen', widget: 'list', field: {label: 'Afbeelding', name: 'image', widget: 'image'} }
      - { label: 'Omschrijving', name: 'body', widget: 'markdown' }
#  - name: 'Paginas'
#    label: 'paginas'
#    folder: '/content'
#    files: 
#      - label: 'Over'
#        name: 'over' 
#        file: 'over.md'
#        fields:
#          - { label: 'Omschrijving', name: 'body', widget: 'markdown' }
