backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'Madelon ter Borg'
    label: 'portfolio'
    folder: 'content/portfolio'
    create: true
    slug: '{{titel}}'
    editor:
      preview: false
    fields:
      - { label: 'Titel', name: 'titel', widget: 'string' }
      - { label: 'Jaar', name: 'date', widget: 'datetime', date_format: 'YYYY' }
      - { label: 'Medium', name: 'medium', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'Link', name: 'link', widget: 'text', required: false }
