backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'Madelon ter Borg'
    label: 'Portfolio'
    folder: '/content/portfolio'
    media_folder: ''
    public_folder: ''
    create: true
    slug: '{{titel}}'
    editor:
      preview: false
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Jaar', name: 'date', widget: 'datetime' }
      - { label: 'Medium', name: 'medium', widget: 'string' }
      - { label: 'Afbeeldingen', name: 'afbeeldingen', widget: 'list', field: {label: 'Afbeelding', name: 'image', widget: 'image'} }
      - { label: 'Omschrijving', name: 'body', widget: 'markdown' }
      - { label: 'Link', name: 'link', widget: 'text', required: false }
  - name: 'Over'
    label: 'over'
    file: '/content/over.md'
    field: 
  - { label: 'Omschrijving', name: 'body', widget: 'markdown' }
