backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'Madelon ter Borg'
    label: 'Portfolio'
    folder: '/content/portfolio/'
    media_folder: ''
    public_folder: ''
    create: true
    slug: '{{titel}}'
    path: '{{slug}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Jaar', name: 'date', widget: 'datetime' }
      - { label: 'Medium', name: 'medium', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'text', required: false }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image', choose_url: false, media_folder: 'thumbnail'  } 
      - { label: 'Afbeeldingen', name: 'afbeeldingen', widget: 'list', field: {label: 'Afbeelding', name: 'image', widget: 'image', choose_url: false, media_folder: 'images'} }
      - { label: 'Omschrijving', name: 'body', widget: 'markdown' }
  - name: 'Paginas'
    label: 'paginas'
    files: 
      - label: 'Over'
        name: 'over' 
        media_folder: ''
        public_folder: ''
        create: false
        editor:
          preview: false
        file: '/content/over.md'
        fields: 
          - { label: 'Portret', name: 'image', widget: 'image', choose_url: false }
          - { label: 'Artist Statement', name: 'body', widget: 'markdown' }
          - label: 'Opleidingen'
            name: 'opleidingen' 
            widget: 'list'
            fields: 
             - { label: 'Opleiding', name: 'opleiding', widget: 'text' }
             - { label: 'Instituut', name: 'plek', widget: 'text' }
             - { label: 'Afstudeerdata', name: 'afstudeerdata', widget: 'text' } 
          - label: 'Tentoonstellingen'
            name: 'tentoonstellingen' 
            widget: 'list'
            fields: 
              - { label: 'Naam', name: 'naam', widget: 'text' }
              - { label: 'Tentoonstellingsruimte', name: 'Tentoonstellingsruimte', widget: 'text' }
              - { label: 'Tentoonstellingsdata', name: 'Tentoonstellingsdata', widget: 'text' } 
              - { label: 'Soort', name: 'soort', widget: 'text' }
          - label: 'Overig'
            name: 'overig' 
            required: false
            widget: 'list'
            fields: 
              - { label: 'Wat', name: 'wat', widget: 'text' }
              - { label: 'Plek', name: 'plek', widget: 'text' }
              - { label: 'Data', name: 'data', widget: 'text' } 
          - { label: 'Email', name: 'email', widget: 'text' }

