backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'Madelon ter Borg'
    label: 'Portfolio'
    folder: '/content/portfolio'
    create: true
    slug: '{{titel}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'titel', widget: 'string' }
      - { label: 'Jaar', name: 'datum', widget: 'datetime' }
      - { label: 'Medium', name: 'medium', widget: 'string' }
      - { label: 'Omschrijving', name: 'omschrijving', widget: 'markdown' }
      - { label: 'Link', name: 'link', widget: 'text', required: false }
