backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'Madelon ter Borg'
    label: 'Portfolio'
    folder: '/content/portfolio/'
    slug: '{{title}}'
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Jaar', name: 'date', widget: 'datetime' }
      - { label: 'Medium', name: 'medium', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'text', required: false }
      - { label: 'Afbeelding', name: 'afbeeldingen', widget: 'list', field: {label: 'Afbeelding', name: 'image', widget: 'image'} }
      - { label: 'Omschrijving', name: 'body', widget: 'markdown' }
  - name: 'Paginas'
    label: 'Paginas'
    files: 
      - label: 'Over'
        name: 'over' 
        media_folder: ''
        public_folder: ''
        create: false
        editor:
          preview: false
        file: '/content/over.md'
        fields:
          - { label: 'Portret', name: 'image', widget: 'image' }
          - { label: 'Omschrijving', name: 'body', widget: 'markdown' }
          - { label: 'Email', name: 'email', widget: 'text' }
 
